FROM python:3.11-slim AS builder

WORKDIR /app


COPY requirements.txt .

RUN pip install --no-cache-dir --target=/deps -r  requirements.txt

#Stage 2 
 
FROM gcr.io/distroless/python3-debian12:nonroot

WORKDIR /app


COPY --from=builder /deps /deps
COPY --chown=nonroot:nonroot . .


ENV PYTHONPATH=/deps

EXPOSE 5001

CMD ["app.py"]
